@URL = https://api.techsoibd.com/api
@USERTOKEN = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS50ZWNoc29pYmQuY29tL2FwaS9sb2dpbiIsImlhdCI6MTc2OTUyMDQyOSwiZXhwIjoxNzY5NTI0MDI5LCJuYmYiOjE3Njk1MjA0MjksImp0aSI6InJCWnBTWklRb3BHQ2E0RmQiLCJzdWIiOiIzIiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.5hpUCmnc8maESxjEtvmzH85_UnujqKS4RCCwDt_dhL4
@ADMINTOKEN = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2FkbWluL2xvZ2luIiwiaWF0IjoxNzY4NTU3MjIzLCJleHAiOjE3Njg1NjA4MjMsIm5iZiI6MTc2ODU1NzIyMywianRpIjoiNUVRTXJzelR0RGtJZ1lDSiIsInN1YiI6IjEiLCJwcnYiOiJkZjg4M2RiOTdiZDA1ZWY4ZmY4NTA4MmQ2ODZjNDVlODMyZTU5M2E5In0.yDVwvCC4NeYubZa5hOB42G9Qs6_pLkxtiKf5sg_pboA

### user login           ---------------> user requests

POST {{URL}}/login
accept: application/json
content-type: application/json

{
    "name": "user one",
    "email": "user1@techsoibd.com",
    "image": "gmail-account-image-url"
}

### user token refresh

GET {{URL}}/refresh
accept: application/json
content-type: application/json
Authorization: Bearer {{USERTOKEN}}

### user info refresh

GET {{URL}}/profile
accept: application/json
content-type: application/json
Authorization: Bearer {{USERTOKEN}}

### user info

GET {{URL}}/logout
accept: application/json
content-type: application/json
Authorization: Bearer {{USERTOKEN}}

### get user favorite product list ----------->favorite product requests

GET {{URL}}/fav-list
accept: application/json
content-type: application/json
Authorization: Bearer {{USERTOKEN}}

### get user favorite product list

POST {{URL}}/fav-list
accept: application/json
content-type: application/json
Authorization: Bearer {{USERTOKEN}}

{
    "product_id": "1"
}

### delete favorite product

DELETE {{URL}}/fav-list/1
accept: application/json
Authorization: Bearer {{USERTOKEN}}

### get user cart product list ----------->cart product requests

GET {{URL}}/cart-product
accept: application/json
content-type: application/json
Authorization: Bearer {{USERTOKEN}}

### get user cart product list

POST {{URL}}/cart-product
accept: application/json
content-type: application/json
Authorization: Bearer {{USERTOKEN}}

{
    "product_id": "1"
}

### delete cart product

DELETE {{URL}}/cart-product/1
accept: application/json
Authorization: Bearer {{USERTOKEN}}

### pay and order             ---------------> pay and order requests

POST {{URL}}/pay/sslcommerz
accept: application/json
content-type: application/json
Authorization: Bearer {{USERTOKEN}}

{
    "name": "MD Al Amin Islam",
    "phone": "01821858917",
    "email": "mi3548514@gmail.com",
    "address": "Mirpur",
    "city": "Dhaka",
    "postcode": "1216",
    "products": [
        {
            "product_id": 60,
            "quantity": 1,
            "amount": 972
        }
    ]
}
# HTTP/1.1 302 Found
# Server: nginx/1.24.0 (Ubuntu)
# Date: Tue, 27 Jan 2026 09:29:48 GMT
# Content-Type: text/html; charset=UTF-8
# Transfer-Encoding: chunked
# Connection: close
# Location: https://sandbox.sslcommerz.com/EasyCheckOut/testcdef3fc3496b440d3d62523bf7af0c9f736



# HTTP/1.1 302 Found
# Server: nginx/1.24.0 (Ubuntu)
# Date: Mon, 26 Jan 2026 17:35:22 GMT
# Content-Type: text/html; charset=UTF-8
# Transfer-Encoding: chunked
# Connection: close
# Location: https://sandbox.sslcommerz.com/EasyCheckOut/testcde6335898191fbc5bc4f0b321a3b674f0c


### user review             ---------------> user review requests

GET {{URL}}/user-review
accept: application/json
content-type: application/json
Authorization: Bearer {{USERTOKEN}}

### admin login             ---------------> admin info requests

POST {{URL}}/admin/login
accept: application/json
content-type: application/json

{
    "email": "admin@techsoibd.com",
    "password": "123"
}

### admin info

GET {{URL}}/admin/profile
accept: application/json
content-type: application/json
Authorization: Bearer {{ADMINTOKEN}}

### admin logout

GET {{URL}}/admin/logout
accept: application/json
content-type: application/json
Authorization: Bearer {{ADMINTOKEN}}

### get order info for admin  ---------------> order requests

GET {{URL}}/order
accept: application/json
content-type: application/json
Authorization: Bearer {{ADMINTOKEN}}

### get single order details

GET {{URL}}/order/1
accept: application/json
content-type: application/json
Authorization: Bearer {{ADMINTOKEN}}

### update order

PUT {{URL}}/order/1
accept: application/json
content-type: application/json
Authorization: Bearer {{ADMINTOKEN}}

{
    "pay_status": "1",
    "status": "1",
}

# pay_status 0 = due, 1 = paid
# status 1 = new order, 2 = panding, 3 = processing, 4 = in delivery, 5 = complete, 0 = cancel

### delete a order

DELETE {{URL}}/order/1
accept: application/json
Authorization: Bearer {{ADMINTOKEN}}

{
    "cancel_message": "Out of Stock",
}

### get order product info  ---------------> order details requests

PUT {{URL}}/order-details/1
accept: application/json
content-type: application/json
Authorization: Bearer {{ADMINTOKEN}}

{
    "pay_status": "1",
    "status": "1",
}

# pay_status 0 = due, 1 = paid
# status 1 = new order, 2 = panding, 3 = processing, 4 = in delivery, 5 = complete, 0 = cancel

### delete a order product

DELETE {{URL}}/order-details/1
accept: application/json
Authorization: Bearer {{ADMINTOKEN}}

{
    "cancel_message": "Out of Stock",
}

### get website basic info  ---------------> full website info requests

GET {{URL}}/website-info
accept: application/json

### update website basic info

PUT {{URL}}/website-info
accept: application/json
content-type: application/json

{
    "email": "test@gamil.com",
    "phone": "01754545454",
    "address": "Chapai",
    "facebook_link": "#",
    "instagram_link": "#",
    "tiktok_link": "#",
    "whatsapp_link": "#"
}

### get all products       ---------------> product requests

GET {{URL}}/product
accept: application/json

### get limited product

GET {{URL}}/product-limit/4
accept: application/json

### get paginated product

GET {{URL}}/product-paginate/4
accept: application/json

### get searching product

GET {{URL}}/product-search/Gaming Mouse
accept: application/json

### get filtered product

GET {{URL}}/product-filter?filter[name]=Gaming Mouse&filter[category_id]=1&sort=-id
accept: application/json

### get details of product

GET {{URL}}/product-details/monarch-city-ranger-x7-argb-mid-tower-atx-desktop-case
accept: application/json

### get single product

GET {{URL}}/product/1
accept: application/json

### store new product

POST {{URL}}/product
accept: application/json
content-type: application/json

{
    "name": "test product 1",
    "regular_price": "2000",
    "discount": "500",
    "sale_price": "1500",
    "main_image": "FORM-URL",
    "category_id": "1",
    "sub_category_id": "1",
    "brand_id": "1",
    "short_description": "short-description",
    "emi_status": "1",
    "full_description": "full-description",
    "specifications": [{"name":"Height","value":"38.6mm"},{"name":"color","value":"red"}],
    "extra_images": [{"url":"FORM-URL-1"},{"url":"FORM-URL-2"}]
}

### update product

PUT {{URL}}/product/1
accept: application/json
content-type: application/json

{
    "name": "test product update",
    "regular_price": "2000",
    "sale_price": "1500",
    "main_image": "FORM-URL",
    "category_id": "1",
    "sub_category_id": "1",
    "brand_id": "1",
    "short_description": "short-description",
}

### delete a product

DELETE {{URL}}/product/1
accept: application/json

### get single product details       ---------------> product details requests

GET {{URL}}/product-details/1
accept: application/json

### update product details

PUT {{URL}}/product-details/1
accept: application/json
content-type: application/json

{
    "product_id": "1",
    "full_description": "full-description",
    "specifications": [{"name":"Height","value":"38.6mm",},{"name":"color","value":"red",}],
    "extra_images": [{ "FORM-URL-1" },{ "FORM-URL-2" },]
}

### get all products review       ---------------> product review requests

GET {{URL}}/review-product
accept: application/json
Authorization: Bearer {{ADMINTOKEN}}

### get single products review

GET {{URL}}/review-product/1
accept: application/json
Authorization: Bearer {{ADMINTOKEN}}

### store new products review

POST {{URL}}/review-product
accept: application/json
content-type: application/json
Authorization: Bearer {{USERTOKEN}}

{
    "product_id": "1",
    "star":"5",
    "message":"customer message"
}

### delete a products review

DELETE {{URL}}/review-product/1
accept: application/json
Authorization: Bearer {{ADMINTOKEN}}

### get all faq             ---------------> faq requests

GET {{URL}}/faq
accept: application/json

### get limited faq

GET {{URL}}/faq-limit/4
accept: application/json

### get single faq

GET {{URL}}/faq/1
accept: application/json

### store new faq

POST {{URL}}/faq
accept: application/json
content-type: application/json

{
    "question": "test-question-1",
    "answer": "test-answer-1"
}

### update a faq

PUT {{URL}}/faq/1
accept: application/json
content-type: application/json

{
    "question": "test-question-up",
    "answer": "test-answer-1"
}

### delete a faq

DELETE {{URL}}/faq/1
accept: application/json

### get all category             ---------------> category requests

GET {{URL}}/category
accept: application/json

### get single category

GET {{URL}}/category/1
accept: application/json

### get limited category

GET {{URL}}/category-limit/4
accept: application/json

### store new category

POST {{URL}}/category
accept: application/json
content-type: application/json

{
    "name": "test-category-1",
    "image": "FORM-URL"
}

### update a category

PUT {{URL}}/category/1
accept: application/json
content-type: application/json

{
    "name": "test-category-1",
    "image": "FORM-URL"
}

### delete a category

DELETE {{URL}}/category/1
accept: application/json

### get all sub-category             ---------------> sub-category requests

GET {{URL}}/sub-category
accept: application/json

### get single sub-category

GET {{URL}}/sub-category/1
accept: application/json

### store new sub-category

POST {{URL}}/sub-category
accept: application/json
content-type: application/json

{
    "category_id": "1",
    "name": "test-sub-category-1",
    "image": "FORM-URL"
}

### update a sub-category

PUT {{URL}}/sub-category/1
accept: application/json
content-type: application/json

{
    "category_id": "1",
    "name": "test-sub-category-1",
    "image": "FORM-URL"
}

### delete a sub-category

DELETE {{URL}}/sub-category/1
accept: application/json

### get all brand             ---------------> brand requests

GET {{URL}}/brand
accept: application/json

### get limited brand

GET {{URL}}/brand-limit/4
accept: application/json

### get single brand

GET {{URL}}/brand/1
accept: application/json

### get special brand

GET {{URL}}/brand-special
accept: application/json

### store new brand

POST {{URL}}/brand
accept: application/json
content-type: application/json

{
    "name": "test-brand-1",
    "image": "FORM-URL",
    "special": 1
}

### update a brand

PUT {{URL}}/brand/1
accept: application/json
content-type: application/json

{
    "name": "test-brand-1",
    "image": "FORM-URL",
    "special": 0
}

### delete a brand

DELETE {{URL}}/brand/1
accept: application/json

### get all special brand             ---------------> special brand requests

GET {{URL}}/special-brand
accept: application/json

### get limited brand

GET {{URL}}/special-brand-limit/4
accept: application/json

### store new brand

POST {{URL}}/special-brand
accept: application/json
content-type: application/json

{
    "image": "FORM-URL",
}

### delete a brand

DELETE {{URL}}/special-brand/1
accept: application/json

### get all Hero Image             ---------------> Hero Image requests

GET {{URL}}/hero-image
accept: application/json

### get limited brand

GET {{URL}}/hero-image-limit/4
accept: application/json

### store new brand

POST {{URL}}/hero-image
accept: application/json
content-type: application/json

{
    "image": "FORM-URL",
}

### delete a brand

DELETE {{URL}}/hero-image/1
accept: application/json

### get all blog             ---------------> blog requests

GET {{URL}}/blog
accept: application/json

### get limited blog

GET {{URL}}/blog-limit/4
accept: application/json

### get single blog

GET {{URL}}/blog/1
accept: application/json

### store new blog

POST {{URL}}/blog
accept: application/json
content-type: application/json

{
    "title": "test-blog-1",
    "image": "FORM-URL",
    "short_description": "test-short-description",
    "full_description": "test-full-description",
}

### update a blog

PUT {{URL}}/blog/1
accept: application/json
content-type: application/json

{
    "title": "test-blog-update",
    "image": "FORM-URL",
    "short_description": "test-short-description",
    "full_description": "test-full-description",
}

### delete a blog

DELETE {{URL}}/blog/1
accept: application/json










{
    "id": 42,
    "product_id": 65,
    "full_description": "Quis natus ratione c",
    "specifications": "[{\"name\":\"Libero esse molliti\",\"value\":\"Duis sapiente conseq\"}]",
    "extra_images": [
        "https://api.techsoibd.com/images/product/65-0-product-ex-image-2026-01-26-06-03-49.png",
        "https://api.techsoibd.com/images/product/65-1-product-ex-image-2026-01-26-06-03-49.png",
        "https://api.techsoibd.com/images/product/65-2-product-ex-image-2026-01-26-06-03-49.png",
        "https://api.techsoibd.com/images/product/65-3-product-ex-image-2026-01-26-06-03-49.png"
    ],
    "created_at": "2026-01-26T18:03:49.000000Z",
    "updated_at": "2026-01-26T18:03:49.000000Z"
}